title: Muffins2.0's code
author: Aaron Charley
email: aaron.charley13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  im a beginner and currently learning computer programming. i may not know much about codes
  but i am willing to learn more about it and other ways to code to be best at it to say that
  i'm a professional at coding.
theme: minima

# social links
twitter_username: (who uses twitter,... oh trump)
github_username:  Aaron-Charley  or Muffins2.0

show_excerpts: true # set to false to remove excerpts on the homepage
